#logger
#logging.file.path=
server:
  port: 5000

websecurity:
  cors:
    corsMappings:
      - path: "/**"
        allowedOrigins:
          - "*"
        allowedHeaders:
          - "*"
        allowedMethods:
          - "*"
        allowCredentials: true
        exposedHeaders:
          - "*"
  jwt:
    enable: false
    secretKey: "VGhlRW5jb2RlQmFzZTY0TXVzdEJlR3JlYXRlclRoYW4yNTZCaXQhISE="
    expiryInMinutes: 90
  oauth:
    enable: false
    registrations:
      - registrationId: github
        clientId: fa986cd9bcb0b4407d47
        clientSecret: d2a84d704a9bb375f68f729bfc5b42b39345f047
        redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
        scope:
          - user:email
          - read:user
      - registrationId: google
        clientId: 952323333916-32g02hqo2ia8gmjmq3f2per14b1qejeo.apps.googleusercontent.com
        clientSecret: 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
        redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
        scope:
          - email
          - profile
    authorizedUrlList:
      - http://localhost:3000/
      - customscheme://testingApp/post_login

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

datasource:
  mariadb:
    url: jdbc:mariadb://neo-sit-db.cilnjlm7rzxc.ap-southeast-2.rds.amazonaws.com:3306/demo2
    username: admin
    password: Admin12345
    dialect: org.hibernate.dialect.MariaDB103Dialect

security:
  oauth2:
    client:
    registration:
      github:
        client-id: fa986cd9bcb0b4407d47
        client-secret: 3bc0f6b8332f93076354c2a5bada2f5a05aea60d
        redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
        scope:
          - user:email
          - read:user

# only for local debugging
debug: true
enableLoggingRequestDetails: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace