#spring.profiles.active=@spri ng.profiles.active@
server:
  servlet:
    context-path: /api

spring:
  profiles:
#    default: LOCAL
    active: @spring.profiles.active@
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    default-property-inclusion: always
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    open-in-view: false
  batch:
    jdbc:
      initialize-schema: never

datasource:
  mysql:
    enable: false
    driverClassName: com.mysql.cj.jdbc.Driver
  mariadb:
    enable: true
    driverClassName: org.mariadb.jdbc.Driver

webclient:
  sync:
    timeout: PT30S
